name: Build AJAX Application - GitHub Package

run-name: "Deploy to @${{ github.ref_name }} by @${{ github.actor }}"

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'Ajax/**/*'
      - '.github/workflows/main_build-ajax.yml'
jobs:  
  build-and-publish:    
    runs-on: windows-latest

    env:
      PROJECT_NAME: NetGitHubActions-POC

    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        #with:
        #  dotnet-version: 4.8.x

      - name: Publish NuGet package      
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      
      - name: Restore NuGet packages
        run: nuget restore ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -PackagesDirectory packages
        # nuget restore ${{ env.PROJECT_NAME }}.sln -ConfigFile NuGet.Config
        env:
            TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }} 
            TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
            NUGET_USER: ${{ github.actor }}
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build the solution
        run: msbuild ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj /p:Configuration=Release
        env:
          PROJECT_DIR: ${{ env.PROJECT_NAME }}
          BUILD_CONFIG: Release

      - name: Show build output
        if: always()
        run: |
          ls -R ${{ env.PROJECT_DIR }}
          echo "BUILD_CONFIG=${{ env.BUILD_CONFIG }}"
          echo "PROJECT_DIR=${{ env.PROJECT_DIR }}"
          echo "PROJECT_FILE=${{ env.PROJECT_DIR }}/${{ env.PROJECT_DIR }}.csproj"
          echo "BUILD_ARTIFACTS=${{ env.PROJECT_DIR }}/bin/${{ env.BUILD_CONFIG }}"

      - name: Create NuGet package
        run: nuget pack ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -Prop Configuration=Release
        env:
          BUILD_ARTIFACTS: ${{ env.PROJECT_NAME }}/bin/Release      
      
      - name: Publish NuGet packag
        run: nuget push ${{ env.PROJECT_NAME }}.*.nupkg -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}